services:
  front:
    build:
      context: ./Front
    ports:
      - "8081:80"
    depends_on:
      - db
      - back

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kebab
    
  back:
    build:
      context: ./Back
    depends_on:
    - db
