# Usar la imagen base de MySQL
FROM mysql:5.7

# Establecer variables de entorno
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=kebab

# Copiar scripts de inicialización si es necesario
COPY ./kebab /docker-entrypoint-initdb.d/